### ISSUE TITLE
Fail on warning

### ISSUE THREAD

**Issue by alex-star-gh** [xdissent/grunt-stylint#1]
[Adding `"error": true` to every single config option is a little silly](https://github.com/rossPatton/stylint#severity), it would be nice if grunt-stylint provided a failOnWarning like [gulp-stylint does](https://github.com/danielhusar/gulp-stylint#failonerror), failing the process on a warning, not just an error.

**Comment by Kristinita** [comment]
@joshstar , why you close issue? It not fixed.

Thanks.
